jobs:

# jobs for the sample node app pipeline from CI thru TEST environment

################################

# add pipeline workflow

# manifest gen for VISUALIZER
  - name: man-sample-gke
    type: manifest
    steps:
      - IN: img-sample-gcr
      - IN: img-opts-sample-test-gke
      - TASK: managed

# TEST deployment to Amazon ECS
  - name: deploy-test-sample-gke
    type: deploy
    steps:
      - IN: man-sample-gke
      - IN: params-sample-test-gke
      - IN: trigger-sample-test-gke
      - IN: cluster-gke
      - TASK: managed

# Create external loadBalancer entrypoint for test service
  - name: service-test-sample-gke
    type: provision
    steps:
      - IN: service-sample-test
      - IN: deploy-test-sample-gke
      - TASK: managed

# # Create release for PROD
#   - name: release-sample-gke
#     type: release
#     steps:
#       - IN: ver-sample-gke
#         switch: off
#       - IN: deploy-test-sample-gke
#         switch: off
#       - IN: trigger-release-prod-gke
#       - TASK:   managed
#         bump: patch

# TEST deployment to Amazon ECS
  - name: deploy-prod-sample-gke
    type: deploy
    steps:
      - IN: deploy-test-sample-gke
        switch: off
      - IN: params-sample-prod-gke
      - IN: img-opts-sample-prod-gke
      - IN: trigger-sample-prod-gke
      - IN: replicas-sample-prod-gke
      - IN: cluster-gke
      - TASK: managed

# Create external loadBalancer entrypoint for prod service
  - name: service-prod-sample-gke
    type: provision
    steps:
      - IN: deploy-prod-sample-gke
      - IN: service-sample-prod
      - TASK: managed
