jobs:

# jobs for the sample node app pipeline from CI thru TEST environment

################################

# add pipeline workflow

# manifest gen for VISUALIZER
  - name: man-sample
    type: manifest
    steps:
      - IN: img-sample
      - IN: img-opts-sample-test
      - TASK: managed

# TEST deployment to Amazon ECS
  - name: test-gke-sample
    type: deploy
    steps:
      - IN: man-sample
      - IN: params-sample-test
      - IN: trigger-sample-test
      - IN: env-gke
      - TASK: managed

# Create release for PROD
  - name: release-sample
    type: release
    steps:
      - IN: ver-sample
        switch: off
      - IN: test-gke-sample
        switch: off
      - IN: trigger-release-prod
      - TASK:   managed
        bump: patch

# PROD deployment to Amazon ECS
  - name: prod-gke-sample
    type: deploy
    steps:
      - IN: release-sample
        switch: off
      - IN: img-opts-sample-prod
      - IN: params-sample-prod
      - IN: replicas-sample-prod
      - IN: trigger-sample-prod
      - IN: env-gke
      - TASK: managed
